apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.deploymentNumber }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}-{{ .Values.deploymentNumber }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
